-- import Palamedes.Synthesizer
-- import Palamedes.Sample

-- open Gen CorrectGen

-- namespace NotUnique

-- @[simp]
-- def isNotUniqueAux (xs : List Nat) (soFar : List Nat) :=
--   match xs with
--   | [] => false
--   | x :: xs' => List.elem x soFar || isNotUniqueAux xs' (x :: soFar)

-- @[simp]
-- def isNotUnique (xs : List Nat) :=
--   isNotUniqueAux xs []

-- set_option palamedes.debug true

-- def genNotUniqueFold : Gen (List Nat) := by
--   -- generator_search (fun xs => List.fold (fun x b soFar => List.elem x soFar || b (x :: soFar)) (fun x => false) xs [] = true)
--   let cg : CorrectGen (fun (xs : List Nat) => List.fold (fun x b soFar => List.elem x soFar || b (x :: soFar)) (fun x => false) xs [] = true) := by
--     -- apply convert (by
--     --   funext
--     --   simp_predicate
--     --   sorry
--     --   --rw [← List.fold_accu_Option_function (by intros; simp_all; apply congr; sorry)]; (try aesop); done
--     --   ) (List.s_unfold _)
--     sorry
--   let g : Gen (List ℕ) := by
--     optimize_gen cg.val
--   -- let _ : support cg.val = support g := by
--   --   optimality
--   -- let _ : Gen.total g := by
--   --   totality
--   exact g

-- @[simp]
-- def notUniqueAccuM (xs : List Nat) : Option Bool :=
--   List.accuM
--     (fun x soFar => x :: soFar)
--     (fun x b soFar => do
--       some (List.elem x soFar || b))
--     (fun _ => false)
--     xs
--     []

-- def genNotUniqueManual : Gen (List Nat) :=
--   List.unfold (fun (b, s) =>
--     if b
--     then pick
--       (do
--       let x ← assume (s.length > 0) (fun h => elements s (by aesop))
--       pure (ListF.cons x (false, x :: s)))
--       (do
--       let x ← arbNat //this could still be a duplicate
--       pure (ListF.cons x (true, x :: s)))
--     else pick
--       (pure ListF.nil)
--       (do
--        let x ← arbNat
--        pure (ListF.cons x (false, x :: s)))
--   ) (true, [])

-- @[reducible]
-- def notUniqueAccuM (xs : List Nat) : Prop :=
--   List.accuM
--     (fun x s => x :: s)
--     (fun x b s => if b || List.elem x s)
--     (fun _ => some false)
--     xs
--     [] = some true

-- def genNotUniqueAccuM : Gen (List Nat) := by
-- --   -- generator_search (fun xs =>
-- --   -- List.accuM (fun x soFar => x :: soFar) (fun x b soFar => some (List.elem x soFar || b)) (fun x => some false) xs [] =
-- --   --   some true)
--   let cg : CorrectGen (fun (xs : List Nat) =>
--   List.accuM
--     (fun x soFar => x :: soFar)
--     (fun x b soFar => some (List.elem x soFar || b))
--     (fun x => some false) xs [] =
--     some true) := by
--     apply convert (by
--       funext
--       simp_predicate
--       rfl) (List.s_unfold _)
--     intros b s

--     simp_predicate
--     --simp [exists_or]
--     -- conv => congr; intro t; rw [or_comm, or_assoc]
--     conv => congr; intro x; lhs; rw [← (@exists_const ( b = false ∧ x = ListF.nil) Nat)]
--     conv => congr; intro x; rw [← (@exists_or Nat)]
--     simp_predicate
--     --apply caseBool (b || List.elem x s)
--     -- . intros
--     --   apply convert (by
--     --     funext
--     --     simp_predicate
--     --     first
--     --     | rfl
--     --     | rw [exists_or]) (s_pick _ _)
--     --   . apply convert (by norm_for_bind) (s_bind _ _)
--     --     . eta_expand
--     --       apply (s_elements_partial _)
--     --     . cgenerator_search
--     --   . sorry --cgenerator_search
--     -- . intros h
--     --   simp_predicate
--     --   rw [exists_o]
--     --   apply convert (by norm_for_pick) (s_pick _ _)
--     --   . cgenerator_search
--     --   . sorry
--   let g : Gen (List ℕ) := by
--     optimize_gen cg.val
--   -- let _ : support cg.val = support g := by
--   --   optimality
--   -- let _ : Gen.total g := by
--   --   totality
--   exact g

-- example (xs : List Nat) :
--   ∃ (m1 : Nat → List Nat → List Nat)
--     (m2 : Nat → Bool → List Nat → Option Bool)
--     (m3 : List Nat → Option Bool)
--     (m4 : List Nat)
--     (m5 : Bool),
--   List.accuM m1 m2 m3 xs m4 = some m5 ↔
--   List.accuM
--   (fun x soFar => x :: soFar)
--   (fun x b soFar => some (List.elem x soFar || b))
--   (fun x => some false) xs [] =
--   some true := by
--   aesop
--   --sorry

-- end NotUnique
