name = "palamedes"
version = "0.1.0"
defaultTargets = ["palamedes"]

[[lean_lib]]
name = "Palamedes"

[[lean_exe]]
name = "palamedes"
root = "Main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.18.0"

[[require]]
name = "aesop"
git = "https://github.com/leanprover-community/aesop"
rev = "v4.18.0"

[[require]]
name = "plausible"
git = "https://github.com/leanprover-community/plausible"
rev = "v4.18.0"
