name = "palamedes"
version = "0.1.0"
defaultTargets = ["palamedes"]

[[lean_lib]]
name = "Palamedes"

[[lean_exe]]
name = "palamedes"
root = "Main"

[[require]]
name = "Parser"
git = "https://github.com/fgdorais/lean4-parser"
rev = "711662ab6f3c4c0080f6379737b41b1089d3d3f8"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.14.0"

[[require]]
name = "plausible"
git = "https://github.com/leanprover-community/plausible"
rev = "v4.14.0"